name: Go build
on:
- push
jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out repository
      uses: actions/checkout@v1

    - name: Linux build
      run: |
        make all

    - name: Upload Linux build
      uses: actions/upload-artifact@v1
      with:
        name: linux-amd64
        path: bin/

    - name: Windows build
      run: |
        make clean
        make bin/main.exe

  docker:
    name: build image
    runs-on: ubuntu-latest
    steps:

      - name: build and push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          tag_with_sha: true
          # Static tag:
          #tags: latest
          # Tag with git tag:
          #tag_with_ref: true
          #push: ${{ startsWith(github.ref, 'refs/tags/') }}

